# render.yaml
services:
  - type: web
    name: discord-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 bot.py"
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
